---
- name: restart peertube
  ansible.builtin.systemd:
    name: container-peertube
    scope: user
    state: restarted
  register: systemd_result
  until: systemd_result is succeeded
  retries: 1
  delay: 3